# Generated by Django 3.0.7 on 2020-06-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('by', 'post')},
        ),
    ]
